### ISSUE TITLE
To the end line!

### ISSUE THREAD

**Issue by allanjamesvestal** [vincegio/airthings-ble#2]
**Is your feature request related to a problem? Please describe.**

No problem, just thanks.

**Describe the solution you'd like**

I want to support this effort — especially as it gets reviewed by Home Assistant developers, and introduces important code-design questions on that project.

**Additional context**

I just bought my first Airthings device and was concerned if it would operate within Home Assistant, since HA 2022.8 changed everything about Bluetooth.

I knew the Home Assistant community would figure this out eventually. (It's one of the few Radon detectors that is locally controllable.) But I never thought I'd Google my problem on _the day my device was delivered_ and see a 'pull request' into `home-assistant/core` that already appears to be 90 percent completed.

That's quite impressive to me, and it seems like your work is causing the core Home Assistant folks to consider a whole new class of nuance more than they've encountered in the past. So this seems like a win-win scenario to me.

I hope we can see you get this 'pull request' into `home-assistant/core` — because it will help me specifically, but more importantly, because it is already making Home Assistant better as a concept.

So thank you for your work, and I am crossing my fingers that you're able to venture on and get this ready to merge into `home-assistant/core`. Even if it takes a couple months, I think it will be worth it to expand HA capabilities in the future.

**Comment by vincegio** [comment]
Thank you for the encouragement :) 
It was interesting to see the whole _branding_ issue come to life, shape up and then be released as a cause of this - although I suspect they have thought about this for a while, seeing how quickly it came together.

It appears to be on the track for 2022.11.0 and I am running the beta as we speak, works nicely. 
Looking forward to continuing on this project and seeing if people have any feedback as it gets released.
