### ISSUE TITLE
View Plus Support

### ISSUE THREAD

**Issue by clearscreen** [vincegio/airthings-ble#5]
Hello!

I am looking into adding View Plus support (to have local integration instead of cloud) and I was wondering if you had any insight into why this may not be supported under the current integration. I have not worked with Bluetooth before so any guidance would be appreciated.

The current behavior in Home Assistant OS is: 
Home Assistant discovers the device using airthings-ble and presents it in the UI. After adding it, no configuration or wizard pops up, and no devices or entities are recognized.

Thank you in advance!

**Comment by clearscreen** [comment]
Additional context~

After adding the integration:
![image](https://user-images.githubusercontent.com/3591741/209975598-433329d1-d65e-4f83-a18d-dd132c13fc9a.png)

After clicking submit on the above screen, the card that is visible under Settings > Devices & Services in HAOS:
![image](https://user-images.githubusercontent.com/3591741/209975848-21bbeb8a-a180-440f-b4a4-0e7ef9cdc4af.png)

A couple of logs:
`2022-12-29 10:38:28.559 DEBUG (MainThread) [homeassistant.components.airthings_ble] Finished fetching airthings_ble data in 4.662 seconds (success: True)`
`2022-12-29 10:38:28.560 DEBUG (MainThread) [homeassistant.components.airthings_ble.sensor] got sensors: {}`

**Comment by LaStrada** [comment]
View Plus doesn't support syncing data over BLE, you have to use the cloud integration for this device.

This repo should filter out view devices from being found.

**Comment by vincegio** [comment]
I'll try to find a way to filter out non-supported devices, sorry about that.

**Comment by LaStrada** [comment]
If you filter out serial numbers starting with `296` and `298`, all View devices will be filtered out
